version: "3.8"

services:
  nginx:
    build:
      context: ./docker/nginx
    ports:
      - "80:80"
    volumes:
      - ./app/public:/app/public:rw,cached
    depends_on:
      - app

  app:
    build:
      context: ./docker
    volumes:
      - ./app:/app:cached
      - ./app/vendor:/app/vendor:cached
    depends_on:
      - database
      - storage

  database:
    image: mariadb:10.7.3-focal
    ports:
      - "3306:3306"
    environment:
      MARIADB_USER: recipe
      MARIADB_PASSWORD: recipe
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: app
    volumes:
      - db-data:/var/lib/mysql:rw
  storage:
    image: minio/minio
    command: server --console-address ":9001" /var/storage-data
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - storage-data:/var/storage-data
volumes:
  db-data:
  storage-data: