version: "3.8"

services:
  nginx:
    build:
      context: ./docker/nginx
    ports:
      - "80:80"
    volumes:
      - ./app/public:/app/public:rw,cached
    depends_on:
      - api

  app:
    build:
      context: ./docker
    volumes:
      - ./app:/app:cached
      - ./app/vendor:/app/vendor:cached
    ports:
      - '9000:9000'
    depends_on:
      - database

  database:
    image: postgres:14.2-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: app
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    volumes:
      - db-data:/var/lib/postgresql/data:rw
volumes:
  db-data: